import {
  User,
  Role,
  Article,
  Category,
  MediaFile,
  Comment,
  Service,
  Application,
  LogEntry,
  DashboardStats,
} from "@/types";

// ==================== Roles ====================
export const mockRoles: Role[] = [
  { id: "1", name: "Admin", description: "Quản trị viên hệ thống" },
  { id: "2", name: "Editor", description: "Biên tập viên nội dung" },
  { id: "3", name: "Viewer", description: "Người xem" },
];

// ==================== Users ====================
export const mockUsers: User[] = [
  {
    id: "1",
    username: "admin",
    email: "admin@caolanhward.gov.vn",
    fullName: "Quản trị hệ thống",
    passwordHash: "hashed_admin_password",
    roleId: "1",
    avatar: "",
    role: mockRoles[0],
    createdAt: "2025-01-15T08:00:00Z",
    updatedAt: "2025-03-10T10:30:00Z",
  },
  {
    id: "2",
    username: "nguyenvana",
    email: "nguyenvana@caolanhward.gov.vn",
    fullName: "Nguyễn Văn A",
    passwordHash: "hashed_editor_password_1",
    roleId: "2",
    avatar: "",
    role: mockRoles[1],
    createdAt: "2025-02-20T09:00:00Z",
    updatedAt: "2025-03-12T14:00:00Z",
  },
  {
    id: "3",
    username: "tranthib",
    email: "tranthib@caolanhward.gov.vn",
    fullName: "Trần Thị B",
    passwordHash: "hashed_editor_password_2",
    roleId: "2",
    avatar: "",
    role: mockRoles[1],
    createdAt: "2025-03-01T07:30:00Z",
    updatedAt: "2025-03-15T09:00:00Z",
  },
  {
    id: "4",
    username: "levanc",
    email: "levanc@caolanhward.gov.vn",
    fullName: "Lê Văn C",
    passwordHash: "hashed_moderator_password_1",
    roleId: "3",
    avatar: "",
    role: mockRoles[2],
    createdAt: "2025-03-05T10:00:00Z",
    updatedAt: "2025-03-16T11:00:00Z",
  },
  {
    id: "5",
    username: "phamthid",
    email: "phamthid@caolanhward.gov.vn",
    fullName: "Phạm Thị D",
    passwordHash: "hashed_moderator_password_2",
    roleId: "3",
    avatar: "",
    role: mockRoles[2],
    createdAt: "2025-03-08T08:30:00Z",
    updatedAt: "2025-03-17T08:00:00Z",
  },
];

// ==================== Categories ====================
export const mockCategories: Category[] = [
  {
    id: "1",
    name: "Tin tức",
    slug: "tin-tuc",
    description: "Tin tức địa phương",
  },
  {
    id: "2",
    name: "Thông báo",
    slug: "thong-bao",
    description: "Thông báo từ UBND",
  },
  {
    id: "3",
    name: "Sự kiện",
    slug: "su-kien",
    description: "Sự kiện sắp diễn ra",
  },
  {
    id: "4",
    name: "Văn hóa",
    slug: "van-hoa",
    description: "Văn hóa - Xã hội",
  },
  {
    id: "5",
    name: "Kinh tế",
    slug: "kinh-te",
    description: "Phát triển kinh tế",
  },
  {
    id: "6",
    name: "Giáo dục",
    slug: "giao-duc",
    description: "Giáo dục - Đào tạo",
  },
];

// ==================== Articles ====================
export const mockArticles: Article[] = [
  {
    id: "1",
    title: "Phường Cao Lãnh tổ chức Lễ hội truyền thống năm 2025",
    slug: "phuong-cao-lanh-to-chuc-le-hoi-truyen-thong-nam-2025",
    content: "<p>Ngày 15/03/2025, UBND Phường Cao Lãnh đã long trọng tổ chức Lễ hội truyền thống thường niên...</p>",
    excerpt: "UBND Phường Cao Lãnh tổ chức lễ hội truyền thống với nhiều hoạt động văn hóa đặc sắc.",
    categoryId: "4",
    authorId: "2",
    category: mockCategories[3],
    author: mockUsers[1],
    status: "published",
    createdAt: "2025-03-15T08:00:00Z",
    publishedAt: "2025-03-15T09:30:00Z",
    updatedAt: "2025-03-15T10:00:00Z",
  },
  {
    id: "2",
    title: "Thông báo về việc tiếp nhận hồ sơ thủ tục hành chính trực tuyến",
    slug: "thong-bao-ve-viec-tiep-nhan-ho-so-thu-tuc-hanh-chinh-truc-tuyen",
    content: "<p>Kể từ ngày 01/04/2025, Phường Cao Lãnh chính thức triển khai hệ thống tiếp nhận hồ sơ trực tuyến...</p>",
    excerpt: "Phường triển khai hệ thống tiếp nhận hồ sơ trực tuyến từ tháng 4.",
    categoryId: "2",
    authorId: "1",
    category: mockCategories[1],
    author: mockUsers[0],
    status: "published",
    createdAt: "2025-03-14T09:00:00Z",
    publishedAt: "2025-03-14T09:00:00Z",
    updatedAt: "2025-03-14T09:00:00Z",
  },
  {
    id: "3",
    title: "Kế hoạch phát triển kinh tế địa phương giai đoạn 2025-2030",
    slug: "ke-hoach-phat-trien-kinh-te-dia-phuong-giai-doan-2025-2030",
    content: "<p>UBND Phường Cao Lãnh ban hành kế hoạch phát triển kinh tế với các mục tiêu cụ thể...</p>",
    excerpt: "Kế hoạch phát triển kinh tế - xã hội giai đoạn mới.",
    categoryId: "5",
    authorId: "2",
    category: mockCategories[4],
    author: mockUsers[1],
    status: "draft",
    createdAt: "2025-03-13T07:30:00Z",
    publishedAt: null,
    updatedAt: "2025-03-16T14:00:00Z",
  },
  {
    id: "4",
    title: "Tổng kết công tác giáo dục năm học 2024-2025",
    slug: "tong-ket-cong-tac-giao-duc-nam-hoc-2024-2025",
    content: "<p>Hội nghị tổng kết năm học 2024-2025 đã diễn ra tại Hội trường UBND phường...</p>",
    excerpt: "Tổng kết thành tích giáo dục năm học vừa qua.",
    categoryId: "6",
    authorId: "3",
    category: mockCategories[5],
    author: mockUsers[2],
    status: "published",
    createdAt: "2025-03-12T10:00:00Z",
    publishedAt: "2025-03-12T10:00:00Z",
    updatedAt: "2025-03-12T10:00:00Z",
  },
  {
    id: "5",
    title: "Chương trình tiêm chủng mở rộng tháng 3/2025",
    slug: "chuong-trinh-tiem-chung-mo-rong-thang-3-2025",
    content: "<p>Trạm Y tế phường phối hợp tổ chức chương trình tiêm chủng mở rộng cho trẻ em...</p>",
    excerpt: "Chương trình tiêm chủng cho trẻ em trên địa bàn phường.",
    categoryId: "1",
    authorId: "3",
    category: mockCategories[0],
    author: mockUsers[2],
    status: "published",
    createdAt: "2025-03-10T08:00:00Z",
    publishedAt: "2025-03-10T08:00:00Z",
    updatedAt: "2025-03-10T08:00:00Z",
  },
  {
    id: "6",
    title: "Hội nghị tiếp xúc cử tri quý I năm 2025",
    slug: "hoi-nghi-tiep-xuc-cu-tri-quy-1-nam-2025",
    content: "<p>Đại biểu HĐND phường tổ chức tiếp xúc cử tri tại các khu phố...</p>",
    excerpt: "Hoạt động tiếp xúc cử tri định kỳ.",
    categoryId: "3",
    authorId: "1",
    category: mockCategories[2],
    author: mockUsers[0],
    status: "draft",
    createdAt: "2025-03-08T09:00:00Z",
    publishedAt: null,
    updatedAt: "2025-03-09T11:00:00Z",
  },
];

// ==================== Media ====================
export const mockMedia: MediaFile[] = [
  {
    id: "1",
    fileName: "le-hoi-2025.jpg",
    filePath: "/uploads/le-hoi-2025.jpg",
    type: "image/jpeg",
    uploadedBy: "2",
    uploadedAt: "2025-03-15T08:00:00Z",
    url: "/uploads/le-hoi-2025.jpg",
    fileType: "image/jpeg",
    fileSize: 2400000,
    createdAt: "2025-03-15T08:00:00Z",
  },
  {
    id: "2",
    fileName: "ubnd-phuong.jpg",
    filePath: "/uploads/ubnd-phuong.jpg",
    type: "image/jpeg",
    uploadedBy: "1",
    uploadedAt: "2025-03-14T09:00:00Z",
    url: "/uploads/ubnd-phuong.jpg",
    fileType: "image/jpeg",
    fileSize: 1800000,
    createdAt: "2025-03-14T09:00:00Z",
  },
  {
    id: "3",
    fileName: "banner-thong-bao.png",
    filePath: "/uploads/banner-thong-bao.png",
    type: "image/png",
    uploadedBy: "3",
    uploadedAt: "2025-03-12T10:00:00Z",
    url: "/uploads/banner-thong-bao.png",
    fileType: "image/png",
    fileSize: 560000,
    createdAt: "2025-03-12T10:00:00Z",
  },
  {
    id: "4",
    fileName: "giao-duc-2025.jpg",
    filePath: "/uploads/giao-duc-2025.jpg",
    type: "image/jpeg",
    uploadedBy: "2",
    uploadedAt: "2025-03-10T08:00:00Z",
    url: "/uploads/giao-duc-2025.jpg",
    fileType: "image/jpeg",
    fileSize: 3200000,
    createdAt: "2025-03-10T08:00:00Z",
  },
  {
    id: "5",
    fileName: "tiem-chung.jpg",
    filePath: "/uploads/tiem-chung.jpg",
    type: "image/jpeg",
    uploadedBy: "3",
    uploadedAt: "2025-03-08T09:00:00Z",
    url: "/uploads/tiem-chung.jpg",
    fileType: "image/jpeg",
    fileSize: 1500000,
    createdAt: "2025-03-08T09:00:00Z",
  },
  {
    id: "6",
    fileName: "kinh-te-dia-phuong.png",
    filePath: "/uploads/kinh-te-dia-phuong.png",
    type: "image/png",
    uploadedBy: "1",
    uploadedAt: "2025-03-06T07:30:00Z",
    url: "/uploads/kinh-te-dia-phuong.png",
    fileType: "image/png",
    fileSize: 890000,
    createdAt: "2025-03-06T07:30:00Z",
  },
];

// ==================== Comments ====================
export const mockComments: Comment[] = [
  {
    id: "1",
    articleId: "1",
    userName: "Nguyễn Văn E",
    articleTitle: "Phường Cao Lãnh tổ chức Lễ hội truyền thống năm 2025",
    content:
      "Lễ hội năm nay tổ chức rất hay, hy vọng năm sau sẽ có thêm nhiều hoạt động.",
    status: "approved",
    createdAt: "2025-03-15T14:00:00Z",
  },
  {
    id: "2",
    articleId: "2",
    userName: "Trần Thị F",
    articleTitle:
      "Thông báo về việc tiếp nhận hồ sơ thủ tục hành chính trực tuyến",
    content: "Rất tiện lợi cho người dân, cảm ơn UBND phường.",
    status: "approved",
    createdAt: "2025-03-14T16:00:00Z",
  },
  {
    id: "3",
    articleId: "5",
    userName: "Lê Văn G",
    articleTitle: "Chương trình tiêm chủng mở rộng tháng 3/2025",
    content: "Cho hỏi lịch tiêm cụ thể là ngày nào?",
    status: "pending",
    createdAt: "2025-03-11T10:30:00Z",
  },
  {
    id: "4",
    articleId: "4",
    userName: "Phạm Thị H",
    articleTitle: "Tổng kết công tác giáo dục năm học 2024-2025",
    content: "Chất lượng giáo dục ngày càng được nâng cao.",
    status: "pending",
    createdAt: "2025-03-13T09:00:00Z",
  },
  {
    id: "5",
    articleId: "1",
    userName: "spam_user",
    articleTitle: "Phường Cao Lãnh tổ chức Lễ hội truyền thống năm 2025",
    content: "Bán hàng online giá rẻ...",
    status: "rejected",
    createdAt: "2025-03-15T20:00:00Z",
  },
];

// ==================== Services ====================
export const mockServices: Service[] = [
  {
    id: "1",
    name: "Đăng ký khai sinh",
    description: "Thủ tục đăng ký khai sinh cho trẻ em sinh tại địa bàn phường.",
    requiredDocuments: "Giấy chứng sinh; CCCD cha/mẹ; Sổ hộ khẩu",
    processingTime: "03 ngày làm việc",
    fee: 0,
    templateFile: "khai-sinh-form.docx",
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-03-01T00:00:00Z",
  },
  {
    id: "2",
    name: "Đăng ký kết hôn",
    description:
      "Thủ tục đăng ký kết hôn cho công dân có hộ khẩu tại phường.",
    requiredDocuments:
      "Tờ khai đăng ký kết hôn; CCCD hai bên; Giấy xác nhận tình trạng hôn nhân",
    processingTime: "05 ngày làm việc",
    fee: 30000,
    templateFile: "ket-hon-form.docx",
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-03-01T00:00:00Z",
  },
  {
    id: "3",
    name: "Xác nhận tình trạng hôn nhân",
    description: "Cấp giấy xác nhận tình trạng hôn nhân.",
    requiredDocuments: "CCCD; Tờ khai đề nghị xác nhận",
    processingTime: "03 ngày làm việc",
    fee: 10000,
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-03-01T00:00:00Z",
  },
  {
    id: "4",
    name: "Chứng thực bản sao",
    description: "Chứng thực bản sao từ bản chính các loại giấy tờ.",
    requiredDocuments: "Bản chính giấy tờ; Bản sao cần chứng thực",
    processingTime: "Trong ngày",
    fee: 2000,
    createdAt: "2025-01-01T00:00:00Z",
    updatedAt: "2025-02-15T00:00:00Z",
  },
  {
    id: "5",
    name: "Đăng ký tạm trú",
    description:
      "Thủ tục đăng ký tạm trú cho công dân đến cư trú tại phường.",
    requiredDocuments: "Phiếu báo thay đổi cư trú; CCCD; Hợp đồng thuê nhà",
    processingTime: "03 ngày làm việc",
    fee: 15000,
    templateFile: "tam-tru-form.docx",
    createdAt: "2025-01-15T00:00:00Z",
    updatedAt: "2025-03-10T00:00:00Z",
  },
];

// ==================== Applications ====================
export const mockApplications: Application[] = [
  {
    id: "1",
    serviceId: "1",
    applicantName: "Nguyễn Văn Minh",
    phone: "0901234567",
    email: "nguyenvanminh@gmail.com",
    status: "pending",
    createdAt: "2025-03-16T08:30:00Z",
    serviceName: "Đăng ký khai sinh",
    citizenName: "Nguyễn Văn Minh",
    service: "Đăng ký khai sinh",
    submittedDate: "2025-03-16T08:30:00Z",
    note: "",
  },
  {
    id: "2",
    serviceId: "2",
    applicantName: "Trần Thị Lan",
    phone: "0911112233",
    email: "tranthilan@gmail.com",
    status: "processing",
    createdAt: "2025-03-15T10:00:00Z",
    serviceName: "Đăng ký kết hôn",
    citizenName: "Trần Thị Lan",
    service: "Đăng ký kết hôn",
    submittedDate: "2025-03-15T10:00:00Z",
    note: "Đang xác minh thông tin",
  },
  {
    id: "3",
    serviceId: "4",
    applicantName: "Lê Hoàng Nam",
    phone: "0988233445",
    email: "lehoangnam@gmail.com",
    status: "done",
    createdAt: "2025-03-14T14:00:00Z",
    serviceName: "Chứng thực bản sao",
    citizenName: "Lê Hoàng Nam",
    service: "Chứng thực bản sao",
    submittedDate: "2025-03-14T14:00:00Z",
    note: "Đã hoàn thành",
  },
  {
    id: "4",
    serviceId: "3",
    applicantName: "Phạm Thị Hoa",
    phone: "0903344556",
    email: "phamthihoa@gmail.com",
    status: "done",
    createdAt: "2025-03-13T09:00:00Z",
    serviceName: "Xác nhận tình trạng hôn nhân",
    citizenName: "Phạm Thị Hoa",
    service: "Xác nhận tình trạng hôn nhân",
    submittedDate: "2025-03-13T09:00:00Z",
    note: "Đã cấp giấy",
  },
  {
    id: "5",
    serviceId: "5",
    applicantName: "Võ Minh Tuấn",
    phone: "0933556677",
    email: "vominhtuan@gmail.com",
    status: "rejected",
    createdAt: "2025-03-12T08:00:00Z",
    serviceName: "Đăng ký tạm trú",
    citizenName: "Võ Minh Tuấn",
    service: "Đăng ký tạm trú",
    submittedDate: "2025-03-12T08:00:00Z",
    note: "Thiếu giấy tờ cần bổ sung",
  },
  {
    id: "6",
    serviceId: "1",
    applicantName: "Đặng Thu Hà",
    phone: "0966112233",
    email: "dangthuha@gmail.com",
    status: "pending",
    createdAt: "2025-03-17T07:30:00Z",
    serviceName: "Đăng ký khai sinh",
    citizenName: "Đặng Thu Hà",
    service: "Đăng ký khai sinh",
    submittedDate: "2025-03-17T07:30:00Z",
    note: "",
  },
  {
    id: "7",
    serviceId: "4",
    applicantName: "Bùi Văn Đức",
    phone: "0977001122",
    email: "buivanduc@gmail.com",
    status: "processing",
    createdAt: "2025-03-16T15:00:00Z",
    serviceName: "Chứng thực bản sao",
    citizenName: "Bùi Văn Đức",
    service: "Chứng thực bản sao",
    submittedDate: "2025-03-16T15:00:00Z",
    note: "Đang xử lý",
  },
];

// ==================== Logs ====================
export const mockLogs: LogEntry[] = [
  {
    id: "1",
    userId: "1",
    action: "Login",
    entity: "Auth",
    createdAt: "2025-03-17T08:00:00Z",
    user: "admin",
    module: "Auth",
    timestamp: "2025-03-17T08:00:00Z",
  },
  {
    id: "2",
    userId: "2",
    action: "Create Article",
    entity: "Articles",
    createdAt: "2025-03-15T08:30:00Z",
    user: "nguyenvana",
    module: "Articles",
    detail: "Phường Cao Lãnh tổ chức Lễ hội truyền thống năm 2025",
    timestamp: "2025-03-15T08:30:00Z",
  },
  {
    id: "3",
    userId: "1",
    action: "Update Service",
    entity: "Services",
    createdAt: "2025-03-14T10:00:00Z",
    user: "admin",
    module: "Services",
    detail: "Đăng ký tạm trú",
    timestamp: "2025-03-14T10:00:00Z",
  },
  {
    id: "4",
    userId: "3",
    action: "Upload Media",
    entity: "Media",
    createdAt: "2025-03-12T10:30:00Z",
    user: "tranthib",
    module: "Media",
    detail: "banner-thong-bao.png",
    timestamp: "2025-03-12T10:30:00Z",
  },
  {
    id: "5",
    userId: "1",
    action: "Delete Comment",
    entity: "Comments",
    createdAt: "2025-03-15T20:30:00Z",
    user: "admin",
    module: "Comments",
    detail: "Spam comment removed",
    timestamp: "2025-03-15T20:30:00Z",
  },
  {
    id: "6",
    userId: "4",
    action: "Approve Comment",
    entity: "Comments",
    createdAt: "2025-03-15T15:00:00Z",
    user: "levanc",
    module: "Comments",
    detail: "Comment by Nguyễn Văn E approved",
    timestamp: "2025-03-15T15:00:00Z",
  },
  {
    id: "7",
    userId: "2",
    action: "Update Article",
    entity: "Articles",
    createdAt: "2025-03-16T14:00:00Z",
    user: "nguyenvana",
    module: "Articles",
    detail: "Kế hoạch phát triển kinh tế",
    timestamp: "2025-03-16T14:00:00Z",
  },
  {
    id: "8",
    userId: "1",
    action: "Create User",
    entity: "Users",
    createdAt: "2025-03-08T08:30:00Z",
    user: "admin",
    module: "Users",
    detail: "Created user phamthid",
    timestamp: "2025-03-08T08:30:00Z",
  },
  {
    id: "9",
    userId: "5",
    action: "Login",
    entity: "Auth",
    createdAt: "2025-03-17T07:00:00Z",
    user: "phamthid",
    module: "Auth",
    timestamp: "2025-03-17T07:00:00Z",
  },
  {
    id: "10",
    userId: "1",
    action: "Update Application",
    entity: "Applications",
    createdAt: "2025-03-14T16:00:00Z",
    user: "admin",
    module: "Applications",
    detail: "Lê Hoàng Nam - Chứng thực bản sao",
    timestamp: "2025-03-14T16:00:00Z",
  },
];

// ==================== Dashboard Stats ====================
export const mockDashboardStats: DashboardStats = {
  totalUsers: 5,
  totalArticles: 6,
  totalServices: 5,
  totalApplications: 7,
};

// ==================== Chart Data ====================
export const articlesPerMonth = {
  labels: ["T10", "T11", "T12", "T1", "T2", "T3"],
  data: [4, 6, 8, 5, 7, 6],
};

export const applicationStatusData = {
  labels: ["Chờ xử lý", "Đang xử lý", "Hoàn thành", "Từ chối"],
  data: [2, 2, 2, 1],
};
